[package]
name = "hello-world-generated"
version = "0.1.0"
authors = ["Orhun ParmaksÄ±z <orhunparmaksiz@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
